task

diff --git a/0x05-processes_and_signals/100-process_and_pid_file b/0x05-processes_and_signals/100-process_and_pid_file
--- a/0x05-processes_and_signals/100-process_and_pid_file
+++ b/0x05-processes_and_signals/100-process_and_pid_file
@@ -1,18 +1,25 @@
 #!/usr/bin/env bash
-# script that creates a file, displays text indefinitely, and catches signals
+# This script creates a PID file, displays messages, and handles signals
 
-function remove_kill {
-    rm -f /var/run/holbertonscript.pid
+pid_file="/var/run/myscript.pid"
+
+# Function to clean up and terminate the script
+cleanup() {
+    echo "Deleting PID file and terminating"
+    rm -f "$pid_file"
     exit
 }
 
-echo $$ > /var/run/holbertonscript.pid
-trap 'echo "I hate the kill command"; remove_kill' SIGTERM
-trap 'echo "Y U no love me?!"; remove_kill' SIGINT
-trap 'remove_kill' SIGQUIT
+# Set up signal handlers
+trap 'cleanup' SIGQUIT SIGTERM
+trap 'echo "Y U no love me?!"' SIGINT
+trap 'echo "I hate the kill command"; cleanup' SIGTERM
 
-while true;
-do
-	echo "To infinity and beyond"
-	sleep 3
+# Create PID file
+echo $$ > "$pid_file"
+
+# Display messages indefinitely
+while true; do
+    echo "To infinity and beyond"
+    sleep 2
 done
